adminpanel/urls.py
from django.urls import path
from django.conf.urls import url, include

from . import views

app_name= "adminpanel"
urlpatterns = [
    path('', views.index, name='index'), 
    path('services/', views.services, name='services'), 
    path('support/', views.support, name='support'),
    path('book/', views.book, name='book'),
    path('history/', views.history, name='history'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('register/', views.register, name='register'),
]
#

api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from api import views
from rest_framework.urlpatterns import format_suffix_patterns
#from rest_framework_simplejwt import views as jwt_views
from rest_framework import routers
import os
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .views import *

from rest_framework_simplejwt import views as jwt_views

router = routers.SimpleRouter()
router.register(r'companies', CompanyViewSet)
router.register(r'users', UserViewSet)
router.register(r'adminusers', AdminUserViewSet)
router.register(r'roles', RoleViewSet)
router.register(r'citys', CityViewSet)
#router.register(r'services', ServiceViewSet)
router.register(r'schedules', ScheduleViewSet)
router.register(r'finished_trains', FinishedTrainViewSet)
router.register(r'images', MyImageViewSet)
router.register(r'timelines', TimeLineViewSet)
router.register(r'timers', TimerViewSet)
router.register(r'train_timers', TrainTimerViewSet)
router.register(r'service_categories', ServiceCategoryViewSet)


from rest_framework.authtoken import views as api_views

urlpatterns = [
    url(r'^', include(router.urls)),
    # path("fill_document/", views.fill_document, name="fill_document"),
    # path("fill_waybill/", views.fill_waybill, name="fill_waybill"),
    # path("set_status/", views.set_status, name="set_status"),
    # path("test/", views.test, name="test"),
    # path("get_coords/", views.get_coords, name="get_coords"),
    # path("get_items/", views.get_items, name="get_items"),
    path("check_code/", views.CheckCode.as_view(), name="check_code"),
    path("send_code/", views.SendCode.as_view(), name="send_code"),
    path("register/", views.Register.as_view(), name="register"),
    path("test/", views.test, name="test"),
    path("book_time/", views.BookTime.as_view(), name="book_time"),
    path("confirm_book/", views.ConfirmBook.as_view(), name="confirm_book"),
    path("get_minutes/", views.GetMinutes.as_view(), name="get_minutes"),
    path("end_train/", views.EndTrain.as_view(), name="end_train"),
    path("decline_book/", views.DeclineBook.as_view(), name="decline_book"),
    path("update_schedules/", views.UpdateSchedules.as_view(), name="update_schedules"),
    path("add_image/", views.AddImage.as_view(), name="add_image"),
    path("update_avatar/", views.UpdateAvatar.as_view(), name="update_avatar"),
    path("add_timeline/", views.AddTimeline.as_view(), name="add_timeline"),
    path("submit_form/", views.SubmitForm.as_view(), name="submit_form"),
    path("submit_question_form/", views.SubmitQuestionForm.as_view(), name="submit_question_form"),
    path("submit_review/", views.SubmitReview.as_view(), name="submit_review"),
    path("download_excel/<int:id>", views.DownloadExcel.as_view(), name="download_excel"),
    path("download_all_excel", views.DownloadAllExcel.as_view(), name="download_all_excel"),    
    path("add_friend/", views.AddFriend.as_view(), name="add_friend"),
    path("add_telegram_friend/", views.AddTelegramFriend.as_view(), name="add_telegram_friend"),    
    path('token/', api_views.obtain_auth_token, name='api-token-auth'),
    path('card_data/<int:id>', views.CardData.as_view(), name='card_data'),
    path('update_telegram_id', views.UpdateTelegramIdByPhone.as_view(), name='update_telegram_id'),
    path('top_users', views.TopUsersByPoints.as_view(), name='top_users'),    
    #path('token/', jwt_views.TokenObtainPairView.as_view(), name='token_obtain_pair'),
    #path('token/refresh/', jwt_views.TokenRefreshView.as_view(), name='token_refresh'),
    #path("set_connection_info/", views.set_database_connection_info, name="set_connection_info"),
    
    #path('<str:filepath>/', views.download_file)
    #
]

urlpatterns = format_suffix_patterns(urlpatterns)

qfit/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from qfit import views

from rest_framework.authtoken import views as rest_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    path('admin-panel/', include('adminpanel.urls')),
    path('', views.index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

adminpanel/models.py
from django.db import models
#from api.models import Company

# Create your models here.

class AdminUser(models.Model):
    username = models.TextField(default='')
    password = models.TextField(default='')
    company = models.ForeignKey("api.Company", on_delete=models.CASCADE, blank=True, null=True)
    def __str__(self):
        return self.username

adminpanel/views.py
from django.shortcuts import render

#from .forms import UserForm, CommentForm, BlogForm
from api.models import *
from adminpanel.models import *

from django.shortcuts import redirect
from django.urls import reverse

#from .modules.hashutils import check_pw_hash, make_pw_hash

#from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from django.utils import timezone

#import smtplib, ssl

#from .modules.sendEmail import send_email
import itertools
from django.http import HttpResponse, JsonResponse, Http404

from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
#from .tokens import account_activation_token
#from django.core.mail import EmailMessage
from django import template
import os
from django.conf import settings

from datetime import datetime
from django.views.decorators.csrf import csrf_exempt

from adminpanel.modules.functions import *
from api.modules.hashutils import check_pw_hash, make_pw_hash
from adminpanel.modules.functions import get_current_user

def login(request):
    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        users = AdminUser.objects.filter(username=username)
        if len(users) == 0:
            return render(request, "login.html", {
                "error": "Неверное имя пользователя!",
                "companies": Company.objects.all()
            })
        user = users.first()
        #if check_pw_hash(password, user.password):
        if password == user.password:
            request.session["user"] = user.id
            request.session["company"] = user.company.id
            return redirect(reverse("adminpanel:index"))
        return render(request, "login.html", {
            "error": "Неверный логин или пароль!",
            "companies": Company.objects.all()
        })
    return render(request, "login.html", {
        "companies": Company.objects.all()
    })

def register(request):
    if request.method == "POST":
        username = request.POST['username']
        password = request.POST['password']
        company_id = request.POST["company"]
        company = Company.objects.get(id=company_id)
        users = AdminUser.objects.filter(username=username) 
        if len(users) > 0:
            return JsonResponse({"error": "Already exist"})
        
        hash_password = make_pw_hash(password)
        
        current_user = AdminUser.objects.create(username=username, password=hash_password, company=company)
        current_user.save()
        
        return redirect(reverse("adminpanel:login"))    
               
    return render(request, "login.html", {
        "success": "NICE"
    })

def index(request):
    current_user = get_current_user(request)
    if not current_user:
        return redirect(reverse("adminpanel:login"))
    train_timers = TrainTimer.objects.filter(company=current_user.company)
    if not current_user:
        return redirect(reverse("adminpanel:login"))
    return render(request, "index.html", {
        "timers": train_timers,
        "company": current_user.company,
        "current_user": current_user,
    })

def support(request):
    current_user = get_current_user(request)
    if not current_user:
        return redirect(reverse("adminpanel:login"))
    return render(request, "support.html", {
        "current_user": current_user,
        "company": current_user.company,
    })

def services(request):
    user = get_current_user(request)
    if not user:
        return redirect(reverse("adminpanel:login"))
    company = user.company
    
    service_categories = ServiceCategory.objects.all()
    return render(request, "settings.html", {
        "current_user": user,
        "company": company,
        "days_of_week": DAYS_OF_WEEK,
        "service_categories": service_categories,
        "tags": ServiceCategory.objects.all()
    })

def book(request):
    current_user = get_current_user(request)
    if not current_user:
        return redirect(reverse("adminpanel:login"))
    current_timers = Timer.objects.filter(company=current_user.company).order_by("book_date")
    return render(request, "book.html", {
        "current_timers": current_timers,
        "current_user": current_user,
        "company": current_user.company,
    })


def history(request):
    current_user = get_current_user(request)
    if not current_user:
        return redirect(reverse("adminpanel:login"))
    histories = FinishedTrain.objects.filter(company=current_user.company).order_by("-start_time")
    return render(request, "history.html", {
        "histories": histories,
        "current_user": current_user,
        "company": current_user.company,
    })

def logout(request): # Пока без выхода
    if request.method == "POST":
        del request.session["user"]
        return redirect(reverse("adminpanel:login"))

adminpanel/templates/base.html
{% load static %}

{% block links %}

    <head>
        <script src="{%static 'js/jquery.min.js'%}"></script>
        <link rel="stylesheet" type="text/css" href="{%static 'css/alertify/alertify.min.css'%}">
        <link rel="stylesheet" type="text/css" href="{%static 'fonts/montserrat_family.css'%}">
        <link rel="stylesheet" type="text/css" href="{%static 'css/alertify/themes/default.min.css'%}">
        <link rel="shortcut icon" href="{%static 'img/logo.png'%}" type="image/x-icon">
        <link rel="stylesheet" href="{%static 'css/root.css'%}">
        <script src="{%static 'js/alertify.js'%}"></script>
        <script src="{%static 'js/functions.js'%}"></script>
		<meta charset="UTF-8" />
		<meta http-equiv="X-UA-Compatible" content="IE=edge" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
        
		<title>Qfit Admin</title>
        <link rel="stylesheet" href="{%static 'bootstrap/css/bootstrap.min.css'%}" />
        <link rel="stylesheet" href="{%static 'css/sidebar.css'%}" />
        
        <style>
            html{
                max-width: 1920px;
                min-width: 1240px;
                margin: auto;
            }
        </style>
        {% block styles %}

        {% endblock %}
    </head>
{% endblock %}



{% block body%}
    <div class="mobile-alert">
        <div class="mobile-title">Версия для телефона не доступна!</div>
    </div>
    <body>
        <!-- The core Firebase JS SDK is always required and must be listed first -->
        <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-app.js"></script>

        <!-- TODO: Add SDKs for Firebase products that you want to use
            https://firebase.google.com/docs/web/setup#available-libraries -->
        <!-- <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-analytics.js"></script>
        <script src="https://www.gstatic.com/firebasejs/8.4.1/firebase-storage.js"></script>
        <script src="{%static 'js/firebase.js'%}"></script> -->
        
       
        <div class="bg_image1 hide-on-mobile"></div>
        <div class="bg_image2 hide-on-mobile"></div>
        <div class="sidebar hide-on-mobile">
                <div class="logo"></div>
                <div class="sidebar-option-menu">
                    <div class="sidebar-option {%block main%}{%endblock%}">
                        <a href="{%url 'adminpanel:index'%}">Главная</a>
                    </div>
                    <div class="sidebar-option {%block book%}{%endblock%}">
                        <a href="{%url 'adminpanel:book'%}">Брони</a>
                    </div>
                    <div class="sidebar-option {%block services%}{%endblock%}">
                        <a href="{%url 'adminpanel:services'%}">Настройки клуба</a>
                    </div>
                    <div class="sidebar-option {%block history%}{%endblock%}">
                        <a href="{%url 'adminpanel:history'%}">История</a>
                    </div>
                    <div class="sidebar-option {%block support%}{%endblock%}">
                        <a href="{%url 'adminpanel:support'%}">Помощь и связь</a>
                    </div>
                    
                    <div class="sidebar-option bottom">
                        <form action="{%url 'adminpanel:logout'%}" method="POST">{%csrf_token%}
                            <button type="submit">Выйти</button>    
                        </form>
                    </div>
                </div>
                
        </div>
        <div class="content hide-on-mobile">
            <div class="header">
                <div class="user-block">
                    <div class="user-block-title-block">
                        <div class="up">{{current_user.username}}</div>
                        <!-- <div class="down">Настройки</div> -->
                    </div>
                    <img class="user-block-image-block" src="{%static 'img/user.svg'%}"/>
                        
                    
                </div>
            </div>
            {%block content%}
        
            {%endblock%}
        </div>
            
       
   </body>
{% endblock %}


{%block scripts%}
{%endblock%}

adminpanel/templates/book.html
{% extends "base.html" %}
{% load static %}

{%block styles %}
    <link rel="stylesheet" href="{%static 'css/book.css'%}">
{% endblock %}

{%block book%}active{%endblock%}

{% block content %}
	<div class="wrap">
        <div class="content-title">
            Брони
        </div>
        <div class="content-under-title">
            {{company.name}}
        </div>
        <div class="scrollable">
            <table id="table_current">
                <tr class="head">
                  <th>Телефон</th>
                  <th>Имя</th>
                  <th>Дата брони</th>
                  <th>Время брони</th>
                  <th>Статус</th>
                </tr>
                {%if not current_timers%}
                    <tr id="no_book">
                        <td colspan="5">В данный момент нет броней!</td>
                    </tr>
                {%endif%}
                {%for timer in current_timers%}
                    <tr id="current{{timer.id}}">
                        <td>{{timer.user.phone}}</td>
                        <td>{{timer.user.name}}</td>
                        <td>{{timer.book_date|date:'Y-m-d'}}</td>
                        <td>{{timer.start_time|date:'H:i'}} - {{timer.end_time|date:'H:i'}}</td>
                        
                        <td>
                            <button id="decline_{{timer.id}}" class="decline_book" onclick="decline(this)">Отклонить</button>
                        </td>
                    </tr>
                {%endfor%}
            </table>
        </div>          
    </div>
{% endblock %}

{%block scripts%}
    <script language="javascript">
        var ws_url = 'wss://' + window.location.host + '/ws/timers/';
        var ticksSocket = new WebSocket(ws_url);

        ticksSocket.onmessage = function(event) {
            var data = JSON.parse(event.data);
            if({{current_user.company.id}} == data["company_id"]){
                if(data["decline_book"] != null){
                    tr = $("#current"+ data["timer_id"]);
                    tr.remove();
                    if($("#table_current tr").length == 1){
                        const empty_tr = document.createElement("tr");
                        empty_tr.id = "no_bbok";
                        empty_tr.innerHTML = `<td colspan="5">В данный момент нет броней!</td>`;
                        document.getElementById('table_current').appendChild(empty_tr);
                    }
                }
                
                if(data["new_book"] != null){
                    if($("#no_book")[0] != null){
                        empty_tr = $("#no_book")[0];
                        empty_tr.remove();
                    }
                    time = data["timer_start"]+" - "+data["timer_end"] + " " + data["timer_day"];
                    const tr = document.createElement('tr');
                    tr.id = "current"+ data["timer_id"];
                    tr.innerHTML = `
                    <td>`+data["timer_user"]+`</td>
                    <td>`+data["timer_user_name"]+`</td>
                    <td>`+time+`</td>
                    
                    <td>
                        <button id="decline_`+data["timer_id"]+`" class="decline_book" onclick="decline(this)">Отклонить</button>
                    </td>
                    `;

                    document.getElementById('table_current').appendChild(tr);

                    
                }
                if(data["book_expired"] != null){
                    tr = $("#current"+data["timer_id"]);
                    tr2 = $("#accepted"+data["timer_id"]);
    
                    tr.remove()
                    tr2.remove()
                }
            }
           
            // do whatever required with received data ...
        };
        ticksSocket.onerror = function(event) {
            var data = JSON.parse(event.data);
            console.log('data', data);
            
        };
    </script>
    <script language="javascript">
        function accept(button){
            token = get_token();
            var timer_id = parseInt(button.id.split("_")[1])
            $.ajax({
                url: "/api/accept_book/", 
                type: "POST",
                headers: {"Authorization": "Token "+token},
                data: {"timer_id": timer_id}
            });
        }
        function decline(button){
            token = get_token();
            var timer_id = parseInt(button.id.split("_")[1])
            $.ajax({
                url: "/api/decline_book/", 
                type: "POST",
                headers: {"Authorization": "Token "+token},
                data: {"timer_id": timer_id}
            });
        }
    </script>
{%endblock%}

adminpanel/templates/history.html
{% extends "base.html" %}
{% load static %}

{%block styles %}
    <link rel="stylesheet" href="{%static 'css/history.css'%}">
{% endblock %}

{%block history%}active{%endblock%}

{% block content %}
	
        <div class="wrap">
            <div class="content-title">
                История посещений
            </div>
            <div class="content-under-title">
                <div class="name">{{company.name}}</div>
                <a href="{%url 'download_excel' company.id%}" download class="download-excel"></a>
                
            </div>
            <div class="scrollable">
                <table id="table">
                    <tr class="head">
                    <th>Телефон</th>
                    <th>Имя</th>
                    <th>Дата брони</th>
                    <th>Время старта</th>
                    <th>Время окончания</th>
                    <th>Кол-во минут</th>
                    <th>Оплата</th>
                    </tr>
                    {%if not histories%}
                        <tr>
                            <td colspan="7" id="empty_tr">В данный момент никто не посещал занятия</td>
                        </tr>
                    {%endif%}
                    {%for history in histories%}
                        <tr id="history{{history.id}}">
                            <td>{{history.user.phone}}</td>
                            <td>{{history.user.name}}</td>
                            <td>{{history.start_time|date:'Y-m-d'}}</td>
                            <td>{{history.start_time|date:'H:i'}}</td>
                            <td>{{history.end_time|date:'H:i'}}</td>
                            <td>{{history.minutes}} минуты</td>
                            <td>{{history.bill}} тг</td>
                        </tr>
                    {%endfor%}
                </table>
            </div>
        </div>
    
    
{% endblock %}

{%block scripts%}
    <script language="javascript">
        var ws_url = 'wss://' + window.location.host + '/ws/timers/';
        var ticksSocket = new WebSocket(ws_url);

        ticksSocket.onmessage = function(event) {
            var data = JSON.parse(event.data);
            if({{current_user.company.id}} == data["company_id"]){
                if(data["new_history"] != null){
                    trs = $("tr");
                    empty_tr = $("#empty_tr")[0];
                    if(trs.length == 2 && empty_tr != null){
                        trs[1].remove();
                    }
                    const tr = document.createElement('tr');

                    tr.id = 'history' + data["history_id"];
                    tr.innerHTML = `

                    <td>`+data["phone"]+`</td>
                    <td>`+data["start_time"].slice(0, -3)+`</td>
                    <td>`+data["end_time"].slice(0, -3)+`</td>
                    <td>`+data["minutes"]+` минуты</td>
                    <td>`+data["bill"]+` тг</td>
                    `;

                    document.getElementById('table').appendChild(tr);
                }
            }
           
            // do whatever required with received data ...
        };
        ticksSocket.onerror = function(event) {
            var data = JSON.parse(event.data);
            console.log('data', data);
            
        };
    </script>
    <script>
        function download_excel(){
            $.ajax({
                url: "/api/download_excel/", 
                type: "POST",
                data:{
                    "company": {{current_user.company.id}}
                },                
                success: function(data){
                    if(data["error"]){
                        console.log(data["error"]);
                    }
                    else{
                        var static_url = data["url"];
                        $("#download-url")[0].href = static_url;
                        $("#download-url")[0].click();
                    }                    
                }
            });
        }
    </script>
{%endblock%}

adminpanel/templates/index.html
{% extends "base.html" %}
{% load static %}

{%block styles %}
    
{% endblock %}

{%block main%}active{%endblock%}

{% block content %}
        <div class="wrap">
            <div class="content-title">
                Сейчас тренируются
            </div>
            <div class="content-under-title">
                {{company.name}}
            </div>
            <div class="scrollable">
                <table id="table">
                    <tr class="head">
                    <th>Телефон</th>
                    <th>Имя</th>
                    <th>Дата старта</th>
                    <th>Время старта</th>
                    
                    
                    </tr>
                    {%if not timers%}
                        <tr id="no_train">
                            <td colspan="4">В данный момент никто не занимается</td>
                        </tr>
                    {%endif%}
                    {%for timer in timers%}
                        <tr id="timer{{timer.id}}">
                            <td>{{timer.user.phone}}</td>
                            <td>{{timer.user.name}}</td>
                            <td>{{timer.start_time|date:'Y-m-d'}}</td>
                            <td>{{timer.start_time|date:'H:i'}}</td>
                            
                        </tr>
                        
                    {%endfor%}
                </table>
            </div>
        </div>
    
    
{% endblock %}

{%block scripts%}
    <script language="javascript">
        var ws_scheme = "wss://"//window.location.protocol == "https:" ? "wss" : "ws";
        //var chat_socket = new ReconnectingWebSocket(ws_scheme + '://' + window.location.host + "/chat" + window.location.pathname);
        var ws_url = ws_scheme + window.location.host + '/ws/timers/';
        var ticksSocket = new WebSocket(ws_url);

        ticksSocket.onmessage = function(event) {
            var data = JSON.parse(event.data);
            if({{current_user.company.id}} == data["company_id"]){
                if(data["minutes"] != null){
                    tr = $("#timer_minutes"+data["id"])[0];
                    if(tr){
                        tr.innerText = data["minutes"] + " минут";
                    }
                }
                if(data["finished_train_id"] != null){
                    tr = $("#timer"+ data["delete_id"]);
                    tr.remove();
                    if($("tr").length == 1){
                        const empty_tr = document.createElement("tr");
                        empty_tr.id = "no_train";
                        empty_tr.innerHTML = `<td colspan="4">В данный момент никто не занимается</td>`;
                        document.getElementById('table').appendChild(empty_tr);
                    }
                }
                if(data["new_timer"] != null){
                    if($("#no_train")[0] != null){
                        empty_tr = $("#no_train");
                        empty_tr.remove();
                    }
                    
                    const tr = document.createElement('tr');

                    tr.id = 'timer' + data["timer_id"];
                    tr.innerHTML = `
                    <td>`+data["timer_user"]+`</td>
                    <td>`+data["timer_start"].slice(0, -3)+`</td>
                    
                    `;

                    document.getElementById('table').appendChild(tr);
                }
            }
           
            // do whatever required with received data ...
        };
        ticksSocket.onerror = function(event) {
            console.log(event);
            var data = JSON.parse(event.data);
            console.log('data', data);
            
        };
    </script>
{%endblock%}

adminpanel/templates/login.html
{%load static%}
<!DOCTYPE html>
<html lang="en">
<head>
    <script src="{%static 'js/jquery.min.js'%}"></script>
    <link rel="stylesheet" type="text/css" href="{%static 'css/alertify/alertify.min.css'%}">
    <link rel="stylesheet" type="text/css" href="{%static 'css/alertify/themes/default.min.css'%}">
    <link rel="shortcut icon" href="{%static 'img/logo.png'%}" type="image/x-icon">
    <link rel="stylesheet" href="{%static 'css/root.css'%}">
    <script src="{%static 'js/alertify.js'%}"></script>
    
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    
    <title>Qfit Admin</title>
    <link rel="stylesheet" href="{%static 'bootstrap/css/bootstrap.min.css'%}" />
    <link rel="stylesheet" href="{%static 'css/sidebar.css'%}" />
    <link rel="stylesheet" href="{%static 'css/login.css'%}" />
</head>
<body>
    <div class="bg_image1"></div>
    <div class="bg_image2" style="left:-10%"></div>
    <div class="login-wrap">
        <div class="login-form">
            <div class="form-logo"></div>
            <form action="{%url 'adminpanel:login'%}" method="POST" autocomplete="chrome-off">{%csrf_token%}
                <div class="login-title">Вход</div>
                <input autocomplete="chrome-off" type="text" name="username" value="" placeholder="Имя пользователя">
                <input autocomplete="chrome-off" type="password" name="password" value="" placeholder="Пароль">
                <button type="submit" class="login-button">Войти</button>
            </form>
        </div>
    </div>
</body>
</html>



<!-- <form action="{%url 'adminpanel:register'%}" method="POST">{%csrf_token%}
    <input type="text" name="username" placeholder="Имя пользователя">
    <input type="password" name="password" placeholder="Пароль">
    <select name="company" id="">
        {%for company in companies%}
            <option value="{{company.id}}">{{company.name}}</option>
        {%endfor%}
    </select>
    <button type="submit">Регистрация</button>
</form> -->